# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 batch: false
 branches:
   include:
     - "*"

pr:
 branches:
   include:
     - "*"

schedules:
  - cron: 0 2 * * *
    always: true
    branches:
      include:
        - master
    displayName: "1am CET UTC+1"

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: BuildStage
  displayName: 'BuildStage'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    timeoutInMinutes: 5
    steps:
      - task: DotNetCoreCLI@2
        displayName: 'dotnet restore'
        inputs:
          command: restore
          feedsToUse: 'select'
      - task: DotNetCoreCLI@2
        displayName: 'dotnet build'
        timeoutInMinutes: 3
        inputs:
          command: build
          arguments: '--no-restore --configuration $(BuildConfiguration)'
      - task: DotNetCoreCLI@2
        displayName: 'dotnet test'
        inputs:
          command: test
          projects: '*.tests/*.tests.csproj'
          arguments: '--no-restore --no-build --configuration $(BuildConfiguration)'
      - task: DotNetCoreCLI@2
        displayName: 'dotnet publish'
        inputs:
          command: 'publish'
          publishWebProjects: true
          arguments: '--no-restore --no-build --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      - task: PublishPipelineArtifact@0
        displayName: 'publish artifact'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'webApp'
          publishLocation: 'Container'
- stage: TestDeployStage
  displayName: 'Test Deployment'
  jobs:
  - deployment: Deploy
    displayName: 'Deployment'
    environment: 'azureDevOpsWorkshop-dev'
    strategy:
     runOnce:
       deploy:
         steps:
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Workshop App Connection'
              appType: 'webApp'
              WebAppName: 'czy1oman-buildstuff-2'
              packageForLinux: '$(System.DefaultWorkingDirectory)/_Classic Pipeline/WebApp/learn-azuredevops.zip'